const condicoesTraduzidasComEmoji = {
    Thunderstorm: "⛈️ Trovoadas",
    Drizzle: "🌦️ Garoa",
    Rain: "🌧️ Chuva",
    Snow: "❄️ Neve",
    Mist: "🌫️ Névoa",
    Smoke: "🚬 Fumaça",
    Haze: "🌫️ Neblina",
    Dust: "🌪️ Poeira",
    Fog: "🌁 Nevoeiro",
    Sand: "🏜️ Areia",
    Ash: "🌋 Cinzas",
    Squall: "🌬️ Rajada",
    Tornado: "🌪️ Tornado",
    Clear: "☀️ Céu limpo",
    Clouds: "☁️ Nuvens"
  };
  
  let mapa = null;
  let map2;
  let marcador = null; // marcador global para não duplicar
  

  const paisInput = document.getElementById('pais');
  
  const capitaisPorPais = {
    "Afeganistão": "Kabul",
    "Albânia": "Tirana",
    "Argélia": "Argel",
    "Samoa Americana": "Pago Pago",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Anguila": "The Valley",
    "Antártica": "Antártica",
    "Antígua e Barbuda": "Saint John's",
    "Argentina": "Buenos Aires",
    "Armênia": "Erevan",
    "Aruba": "Oranjestad",
    "Austrália": "Canberra",
    "Áustria": "Viena",
    "Azerbaijão": "Bacu",
    "Bahamas": "Nassau",
    "Bahrein": "Manama",
    "Bangladesh": "Daca",
    "Barbados": "Bridgetown",
    "Bielorrússia": "Minsk",
    "Bélgica": "Bruxelas",
    "Belize": "Belmopan",
    "Benin": "Porto Novo",
    "Bermudas": "Hamilton",
    "Butão": "Thimphu",
    "Bolívia": "Sucre",
    "Bonaire, Santo Eustáquio e Saba": "Kralendijk",
    "Bósnia e Herzegovina": "Sarajevo",
    "Botsuana": "Gaborone",
    "Ilha Bouvet": "Ilha Bouvet",
    "Brasil": "Brasília",
    "Território Britânico do Oceano Índico": "Diego Garcia",
    "Brunei": "Bandar Seri Begawan",
    "Bulgária": "Sófia",
    "Burquina Faso": "Ouagadougou",
    "Burundi": "Bujumbura",
    "Camboja": "Phnom Penh",
    "Camarões": "Yaoundé",
    "Canadá": "Ottawa",
    "Cabo Verde": "Praia",
    "Ilhas Cayman": "George Town",
    "República Centro-Africana": "Bangui",
    "Chade": "N'Djamena",
    "Chile": "Santiago",
    "China": "Pequim",
    "Ilha Christmas": "Flying Fish Cove",
    "Ilhas Cocos (Keeling)": "West Island",
    "Colômbia": "Bogotá",
    "Comores": "Moroni",
    "Coreia do Sul": "Seul",
    "Coreia do Norte": "Pyongyang",
    "Congo": "Brazzaville",
    "Congo (República Democrática do)": "Kinshasa",
    "Ilhas Cook": "Avarua",
    "Costa Rica": "San José",
    "Costa do Marfim": "Yamusukro",
    "Croácia": "Zagreb",
    "Cuba": "Havana",
    "Curaçao": "Willemstad",
    "Chipre": "Nicósia",
    "República Tcheca": "Praga",
    "Dinamarca": "Copenhague",
    "Djibuti": "Djibuti",
    "Dominica": "Roseau",
    "República Dominicana": "Santo Domingo",
    "Equador": "Quito",
    "Egito": "Cairo",
    "El Salvador": "San Salvador",
    "Guiné Equatorial": "Malabo",
    "Eritreia": "Asmara",
    "Estônia": "Tallin",
    "Etiópia": "Adis Abeba",
    "Ilhas Malvinas": "Stanley",
    "Ilhas Faroe": "Tórshavn",
    "Fiji": "Suva",
    "Finlândia": "Helsinque",
    "França": "Paris",
    "Guiana Francesa": "Caiena",
    "Polinésia Francesa": "Papeete",
    "Portugal": "Lisboa",
    "Territórios Franceses do Sul": "Port-aux-Français",
    "Gabão": "Libreville",
    "Gâmbia": "Banjul",
    "Geórgia": "Tbilisi",
    "Alemanha": "Berlim",
    "Gana": "Acra",
    "Gibraltar": "Gibraltar",
    "Grécia": "Atenas",
    "Groenlândia": "Nuuk",
    "Granada": "Saint George's",
    "Guadalupe": "Basse-Terre",
    "Guam": "Hagåtña",
    "Guatemala": "Cidade da Guatemala",
    "Guernsey": "St. Peter Port",
    "Guiné": "Conakri",
    "Guiné-Bissau": "Bissau",
    "Guiana": "Georgetown",
    "Haiti": "Porto Príncipe",
    "Havaí": "Honolulu",
    "McDonald": "McDonald",
    "Vaticano": "Cidade do Vaticano",
    "Honduras": "Tegucigalpa",
    "Hong Kong": "Hong Kong",
    "Hungria": "Budapeste",
    "Islândia": "Reiquiavique",
    "Índia": "Nova Délhi",
    "Indonésia": "Jacarta",
    "Irã": "Teerã",
    "Iraque": "Bagdá",
    "Irlanda": "Dublin",
    "Ilha de Man": "Douglas",
    "Israel": "Jerusalém",
    "Itália": "Roma",
    "Jamaica": "Kingston",
    "Japão": "Tóquio",
    "Jersey": "Saint Helier",
    "Jordânia": "Amã",
    "Cazaquistão": "Astana",
    "Quênia": "Nairóbi",
    "Kiribati": "Bairiki",
    "Kuwait": "Cuaite",
    "Quirguistão": "Bishkek",
    "Laos": "Vientiane",
    "Letônia": "Riga",
    "Líbano": "Beirute",
    "Lesoto": "Maseru",
    "Libéria": "Monróvia",
    "Líbia": "Trípoli",
    "Liechtenstein": "Vaduz",
    "Lituânia": "Vílnius",
    "Luxemburgo": "Luxemburgo",
    "Macau": "Macau",
    "Macedônia do Norte": "Skopje",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malásia": "Kuala Lumpur",
    "Maldivas": "Malé",
    "Mali": "Bamaco",
    "Malta": "Valeta",
    "Ilhas Marshall": "Majuro",
    "Martinica": "Fort-de-France",
    "Mauritânia": "Nouakchott",
    "Maurício": "Port Louis",
    "México": "Cidade do México",
    "Micronésia": "Palikir",
    "Moldávia": "Chisinau",
    "Mônaco": "Mônaco",
    "Mongólia": "Ulaanbaatar",
    "Montenegro": "Podgorica",
    "Montserrat": "Plymouth",
    "Marrocos": "Rabat",
    "Moçambique": "Maputo",
    "Mianmar": "Naypyidaw",
    "Namíbia": "Windhoek",
    "Nauru": "Yaren",
    "Nepal": "Catmandu",
    "Países Baixos": "Amsterdã",
    "Nova Caledônia": "Nouméa",
    "Nova Zelândia": "Wellington",
    "Nicarágua": "Manágua",
    "Níger": "Niamey",
    "Nigéria": "Abuja",
    "Niue": "Alofi",
    "Ilha Norfolk": "Kingston",
    "Ilhas Marianas do Norte": "Saipan",
    "Noruega": "Oslo",
    "Omã": "Mascate",
    "Paquistão": "Islamabad",
    "Palau": "Ngerulmud",
    "Palestina": "Ramala",
    "Panamá": "Cidade do Panamá",
    "Papua-Nova Guiné": "Port Moresby",
    "Paraguai": "Assunção",
    "Peru": "Lima",
    "Filipinas": "Manila",
    "Ilhas Pitcairn": "Adamstown",
    "Polônia": "Varsóvia",
    "Porto Rico": "San Juan",
    "Catar": "Doha",
    "Romênia": "Bucareste",
    "Rússia": "Moscou",
    "Ruanda": "Kigali",
    "Reunião": "Saint-Denis",
    "São Bartolomeu": "Gustavia",
    "Santa Helena": "Jamestown",
    "São Cristóvão e Névis": "Basseterre",
    "Santa Lúcia": "Castries",
    "São Martinho": "Marigot",
    "São Pedro e Miquelão": "Saint-Pierre",
    "São Vicente e Granadinas": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "Cidade de San Marino",
    "São Tomé e Príncipe": "São Tomé",
    "Arábia Saudita": "Riad",
    "Senegal": "Dacar",
    "Sérvia": "Belgrado",
    "Seychelles": "Vitória",
    "Serra Leoa": "Freetown",
    "Singapura": "Singapura",
    "Eslováquia": "Bratislava",
    "Eslovênia": "Liubliana",
    "Ilhas Salomão": "Honiara",
    "Somália": "Mogadíscio",
    "África do Sul": "Pretória",
    "Geórgia do Sul e Ilhas Sandwich do Sul": "King Edward Point",
    "Sudão do Sul": "Juba",
    "Espanha": "Madri",
    "Sri Lanka": "Sri Jayawardenepura Kotte",
    "Sudão": "Cartum",
    "Suriname": "Paramaribo",
    "Eswatini": "Mbabane",
    "Suécia": "Estocolmo",
    "Suíça": "Berna",
    "Síria": "Damasco",
    "Taiwan": "Taipei",
    "Tajiquistão": "Dushanbe",
    "Tanzânia": "Dodoma",
    "Tailândia": "Bangcoc",
    "Timor-Leste": "Díli",
    "Togo": "Lomé",
    "Toquelau": "Fakaofo",
    "Tonga": "Nukualofa",
    "Trinidad e Tobago": "Porto Espanha",
    "Tunísia": "Túnis",
    "Turquia": "Ancara",
    "Turcomenistão": "Ashgabat",
    "Tuvalu": "Funafuti",
    "Uganda": "Kampala",
    "Ucrânia": "Quieve",
    "Emirados Árabes Unidos": "Abu Dhabi",
    "Reino Unido": "Londres",
    "Estados Unidos": "Washington, D.C.",
    "Uruguai": "Montevidéu",
    "Uzbequistão": "Tashkent",
    "Vanuatu": "Port Vila",
    "Venezuela": "Caracas",
    "Vietnã": "Hanói",
    "Ilhas Virgens Britânicas": "Road Town",
    "Ilhas Virgens Americanas": "Charlotte Amalie",
    "Saara Ocidental": "El Aiune",
    "Iémen": "Sanaa",
    "Zâmbia": "Lusaca",
    "Zimbábue": "Harare"
  };
  
  const codigosPais = {
    "Afeganistão": "AF",
    "Albânia": "AL",
    "Argélia": "DZ",
    "Samoa Americana": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguila": "AI",
    "Antártica": "AQ",
    "Antígua e Barbuda": "AG",
    "Argentina": "AR",
    "Armênia": "AM",
    "Aruba": "AW",
    "Austrália": "AU",
    "Áustria": "AT",
    "Azerbaijão": "AZ",
    "Bahamas": "BS",
    "Bahrein": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Bielorrússia": "BY",
    "Bélgica": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermudas": "BM",
    "Butão": "BT",
    "Bolívia": "BO",
    "Bonaire, Santo Eustáquio e Saba": "BQ",
    "Bósnia e Herzegovina": "BA",
    "Botsuana": "BW",
    "Ilha Bouvet": "BV",
    "Brasil": "BR",
    "Território Britânico do Oceano Índico": "IO",
    "Brunei": "BN",
    "Bulgária": "BG",
    "Burquina Faso": "BF",
    "Burundi": "BI",
    "Camboja": "KH",
    "Camarões": "CM",
    "Canadá": "CA",
    "Cabo Verde": "CV",
    "Ilhas Cayman": "KY",
    "República Centro-Africana": "CF",
    "Chade": "TD",
    "Chile": "CL",
    "China": "CN",
    "Ilha Christmas": "CX",
    "Ilhas Cocos (Keeling)": "CC",
    "Colômbia": "CO",
    "Comores": "KM",
    "Coreia do Sul": "KR",
    "Coreia do Norte": "KP",
    "Congo": "CG",
    "Congo (República Democrática do)": "CD",
    "Ilhas Cook": "CK",
    "Costa Rica": "CR",
    "Costa do Marfim": "CI",
    "Croácia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Chipre": "CY",
    "República Tcheca": "CZ",
    "Dinamarca": "DK",
    "Djibuti": "DJ",
    "Dominica": "DM",
    "República Dominicana": "DO",
    "Equador": "EC",
    "Egito": "EG",
    "El Salvador": "SV",
    "Guiné Equatorial": "GQ",
    "Eritreia": "ER",
    "Estônia": "EE",
    "Etiópia": "ET",
    "Ilhas Malvinas": "FK",
    "Ilhas Faroe": "FO",
    "Fiji": "FJ",
    "Finlândia": "FI",
    "França": "FR",
    "Guiana Francesa": "GF",
    "Polinésia Francesa": "PF",
    "Portugal": "PT",
    "Territórios Franceses do Sul": "TF",
    "Gabão": "GA",
    "Gâmbia": "GM",
    "Geórgia": "GE",
    "Alemanha": "DE",
    "Gana": "GH",
    "Gibraltar": "GI",
    "Grécia": "GR",
    "Groenlândia": "GL",
    "Granada": "GD",
    "Guadalupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guiné": "GN",
    "Guiné-Bissau": "GW",
    "Guiana": "GY",
    "Haiti": "HT",
    "Ilhas Heard e McDonald": "HM",
    "Vaticano": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungria": "HU",
    "Islândia": "IS",
    "Índia": "IN",
    "Indonésia": "ID",
    "Irã": "IR",
    "Iraque": "IQ",
    "Irlanda": "IE",
    "Ilha de Man": "IM",
    "Israel": "IL",
    "Itália": "IT",
    "Jamaica": "JM",
    "Japão": "JP",
    "Jersey": "JE",
    "Jordânia": "JO"
  };

  paisInput.addEventListener('keydown', function(event){
    if (event.key === 'Enter') {
      inputbusca.focus();
    }
  })

function obterDirecaoVento(deg) {
  if ((deg >= 348.75 && deg <= 360) || (deg >= 0 && deg < 11.25)) return "Norte ↓";
  else if (deg >= 11.25 && deg < 33.75) return "Norte-Nordeste (↙)";
  else if (deg >= 33.75 && deg < 56.25) return "Nordeste (↙)";
  else if (deg >= 56.25 && deg < 78.75) return "Leste-Nordeste (↙)";
  else if (deg >= 78.75 && deg < 101.25) return "Leste (←)";
  else if (deg >= 101.25 && deg < 123.75) return "Leste-Sudeste (↘)";
  else if (deg >= 123.75 && deg < 146.25) return "Sudeste (↘)";
  else if (deg >= 146.25 && deg < 168.75) return "Sul-Sudeste (↘)";
  else if (deg >= 168.75 && deg < 191.25) return "Sul (↑)";
  else if (deg >= 191.25 && deg < 213.75) return "Sul-Sudoeste (↗)";
  else if (deg >= 213.75 && deg < 236.25) return "Sudoeste (↗)";
  else if (deg >= 236.25 && deg < 258.75) return "Oeste-Sudoeste (↗)";
  else if (deg >= 258.75 && deg < 281.25) return "Oeste (→)";
  else if (deg >= 281.25 && deg < 303.75) return "Oeste-Noroeste (↖)";
  else if (deg >= 303.75 && deg < 326.25) return "Noroeste (↖)";
  else if (deg >= 326.25 && deg < 348.75) return "Norte-Noroeste (↖)";
  else return "Desconhecido";
}
